version: '3.8'

services:
  ubuntu-target:
    image: ubuntu:20.04
    container_name: ubuntu-target
    restart: unless-stopped
    tty: true
    networks:
      - ogent_network
    volumes:
      - ubuntu-target-data:/home/ubuntu
    command: >
      bash -c "
        apt-get update && 
        apt-get install -y openssh-server sudo vim curl wget python3 python3-pip nodejs npm git &&
        mkdir -p /run/sshd && 
        echo 'root:password' | chpasswd && 
        sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && 
        useradd -m -s /bin/bash ubuntu && 
        echo 'ubuntu:ubuntu' | chpasswd && 
        usermod -aG sudo ubuntu && 
        echo 'ubuntu ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && 
        /usr/sbin/sshd -D
      "
    ports:
      - "2222:22"  # Map SSH to external port

  command-execution:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: command-execution
    restart: unless-stopped
    depends_on:
      - ubuntu-target
    networks:
      - ogent_network
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - command-execution-data:/tmp/executions

networks:
  ogent_network:
    external: true

volumes:
  ubuntu-target-data:
  command-execution-data: 