version: '3'

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ogent-auth-service
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage
    networks:
      - ogent-network
    depends_on:
      - auth-db

  auth-nginx:
    image: nginx:alpine
    container_name: ogent-auth-nginx
    restart: unless-stopped
    ports:
      - "8010:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ogent-network
    depends_on:
      - auth-service

  auth-db:
    image: postgres:14-alpine
    container_name: ogent-auth-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-auth_service}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - ogent-network

volumes:
  auth-db-data:

networks:
  ogent-network:
    external: true 